#config/redis.yml
default:
  host: redis-14682.c10.us-east-1-4.ec2.cloud.redislabs.com
  port: 14682
  password: bookedit123
development:
  host: localhost
  port: 6379
  password:
  db: 0
#  namespace: appname_dev
test:
  db: 0
#  namespace: appname_test
production:
  db: 0
  host: redis-14682.c10.us-east-1-4.ec2.cloud.redislabs.com
#  namespace: appname_prod
